/* =========================================================
   Distillation Lab — content data (transcribed from notes PDF)
   ========================================================= */

const PROCESSES = [
  /* ---------------- SIMPLE ---------------- */
  {
    id: 'simple',
    name: 'Simple Distillation',
    short: 'Simple',
    ico: '⚗️',
    color: '#2563eb',
    tagline: 'The simplest method of distillation — a single still, one condenser, one go.',
    useWhen: 'Use when ΔTb > 25–30 °C, or to remove non-volatile impurities',
    definition: 'Simple distillation is the simplest method of distillation. It is used to separate a liquid from non-volatile impurities, or to separate two miscible liquids having a large difference in boiling points (ΔTb > 25–30 °C).',
    principle: [
      'The feed is heated in a still.',
      'The more volatile component vaporizes first.',
      'Vapours rise and pass through the condenser.',
      'In the condenser, vapours are cooled and condensed.',
      'Condensed liquid (distillate) is collected in a receiver.',
      'The less volatile component remains in the still as residue.',
    ],
    steps: [
      'Feed is charged into the still and steam is passed through the jacket.',
      'The mixture is heated — the more volatile component vaporizes.',
      'Vapours pass into the condenser.',
      'Cooling water enters at the bottom of the condenser and leaves at the top.',
      'Vapours condense and the liquid (distillate) collects in receivers R1/R2.',
      'The less volatile component remains in the still as residue.',
    ],
    applications: ['Purification of liquids', 'Separation of liquids with large boiling point difference', 'Recovery of solvents', 'Desalination of water'],
    advantages: ['Simple construction and easy operation', 'Low initial cost', 'Suitable for large boiling point differences', 'Easy to clean and maintain', 'Can handle high feed rates'],
    limitations: ['Not suitable for close-boiling-point liquids', 'Low separation efficiency', 'Higher energy consumption', 'Not used for azeotropic mixtures'],
    legend: [
      { c: '#2563eb', t: 'Feed — mixture to be separated' },
      { c: '#d9480f', t: 'Steam — heats the still (through jacket)' },
      { c: '#5b6675', t: 'Residue — bottom product (less volatile)' },
      { c: '#1a7f4e', t: 'Distillate — top product (more volatile)' },
      { c: '#1098ad', t: 'Coolant — cooling water' },
    ],
    trouble: [
      { s: 'Low distillate rate', c: ['Insufficient heating', 'Fouled reboiler'], a: ['Increase heat input', 'Clean the reboiler'] },
      { s: 'Low product purity', c: ['High-boiling impurities in feed', 'Too fast distillation rate'], a: ['Reduce distillation rate', 'Clean up feed quality'] },
      { s: 'High pressure in system', c: ['Condenser blocked', 'Vent line blocked'], a: ['Clean condenser', 'Clear vent line'] },
      { s: 'Temperature fluctuation', c: ['Unstable heat supply', 'Irregular feed'], a: ['Stabilize heat input', 'Maintain steady feed'] },
      { s: 'Foaming in column', c: ['Presence of surface-active impurities'], a: ['Add antifoam agent', 'Reduce heat input'] },
      { s: 'Bumping in reboiler', c: ['Sudden boiling due to superheating'], a: ['Boil gently', 'Use boiling chips'] },
      { s: 'Leakage', c: ['Loose connections / gasket failure'], a: ['Tighten connections', 'Replace gasket'] },
      { s: 'Low recovery', c: ['Poor condensation', 'Heat loss'], a: ['Improve cooling', 'Insulate system'] },
    ],
  },

  /* ---------------- FRACTIONAL ---------------- */
  {
    id: 'fractional',
    name: 'Fractional Distillation',
    short: 'Fractional',
    ico: '🧪',
    color: '#7048e8',
    tagline: 'A fractionating column with trays or packing gives repeated vapour–liquid contact for close-boiling mixtures.',
    useWhen: 'Use when components have close boiling points (petroleum refining, alcohol purification)',
    definition: 'Fractional distillation is a process used to separate a liquid mixture into its components having close boiling points by using a fractionating column.',
    principle: [
      'It is based on the difference in volatility of the components — the more volatile component rises in the vapour phase and the less volatile component remains in the liquid phase.',
      'Repeated contact of vapour and liquid on trays / packing gives much better separation than a single stage.',
      'Key point: more volatile component → top (distillate); less volatile component → bottoms (residue).',
    ],
    steps: [
      'Feed is introduced into the column.',
      'Reboiler heats the bottom liquid and vapour is generated.',
      'Vapour rises upward through the column.',
      'Liquid from upper trays flows downward.',
      'On each tray / packing, vapour and liquid contact each other.',
      'The more volatile component goes to the top, the less volatile to the bottom.',
      'Top vapour is condensed in the condenser.',
      'Condensed liquid is collected in the reflux drum.',
      'Part of it is returned to the column as reflux; the rest is withdrawn as distillate (top product).',
      'Bottom liquid is withdrawn as bottoms (residue).',
    ],
    applications: ['Separation of liquids having close boiling points', 'Petroleum refining (crude oil)', 'Solvent recovery', 'Alcohol purification', 'Chemical industries'],
    advantages: ['Can separate liquids having close boiling points', 'High purity of products', 'Continuous operation possible', 'Better efficiency'],
    limitations: ['High initial cost', 'More energy requirement', 'Operation is complex', 'Flooding, weeping, entrainment etc. may occur'],
    extras: {
      equipment: ['Fractionating column', 'Reboiler', 'Condenser', 'Reflux drum', 'Reflux pump', 'Trays / packing', 'Feed inlet', 'Bottoms outlet', 'Distillate outlet'],
      trays: ['Sieve tray', 'Valve tray', 'Bubble-cap tray'],
      packing: ['Random packing — Raschig ring, Pall ring, Saddle', 'Structured packing — e.g. structured sheet, Mellapak'],
    },
    legend: [
      { c: '#d9480f', t: 'Vapour — rises up the column' },
      { c: '#1971c2', t: 'Liquid — flows down the column' },
      { c: '#1a7f4e', t: 'Distillate — top product (light)' },
      { c: '#5b6675', t: 'Bottoms (residue) — heavy product' },
    ],
    trouble: [
      { s: 'Low separation efficiency', c: ['Less number of trays', 'Improper reflux ratio'], a: ['Increase number of trays', 'Optimize reflux ratio'] },
      { s: 'Flooding in column', c: ['High vapour velocity', 'Excessive feed rate'], a: ['Reduce vapour rate', 'Reduce feed rate'] },
      { s: 'Weeping', c: ['Low vapour velocity', 'High reflux ratio'], a: ['Increase vapour rate', 'Reduce reflux'] },
      { s: 'Low distillate quality', c: ['Poor reflux', 'Tray weeping or damage'], a: ['Increase reflux ratio', 'Check and clean trays'] },
      { s: 'High pressure drop', c: ['Tray hole blockage', 'Fouling / scale formation'], a: ['Clean trays', 'Remove scale'] },
      { s: 'Irregular level in column', c: ['Unstable feed', 'Overhead condenser issue'], a: ['Stabilize feed', 'Check condenser'] },
      { s: 'Temperature profile irregular', c: ['Faulty temperature sensors', 'Uneven heat input'], a: ['Calibrate sensors', 'Ensure even heating'] },
      { s: 'Low bottom product withdrawal', c: ['Sump level low', 'Bottom valve partially closed'], a: ['Maintain proper level', 'Fully open bottom valve'] },
      { s: 'Entrainment of liquid', c: ['High vapour velocity', 'Damaged internals'], a: ['Reduce vapour rate', 'Check & repair internals'] },
      { s: 'Reboiler fouling', c: ['Scale / polymer deposits', 'Poor quality feed'], a: ['Clean reboiler', 'Improve feed quality'] },
    ],
  },

  /* ---------------- FLASH ---------------- */
  {
    id: 'flash',
    name: 'Flash Distillation',
    short: 'Flash',
    ico: '⚡',
    color: '#d9480f',
    tagline: 'One valve, one drum — partial vaporization by a sudden pressure drop, no heat added.',
    useWhen: 'Use for a single equilibrium stage: light-ends removal, degassing, pre-separation',
    definition: 'Flash distillation (or flash vaporization) is a single-stage equilibrium separation process in which a feed is partially vaporized by a sudden reduction in pressure (at nearly constant temperature), producing a vapour and a liquid stream in equilibrium.',
    principle: [
      'When the pressure of a liquid mixture is reduced suddenly (throttling), its boiling point decreases.',
      'Part of the liquid "flashes" into vapour until vapour–liquid equilibrium is reached at the lower pressure.',
      'The two phases are then separated in the flash drum.',
    ],
    steps: [
      'Pressurised liquid feed (P₁, T₁, zᵢ) enters the throttling valve.',
      'The sudden pressure reduction across the valve causes partial vaporization.',
      'The two-phase mixture enters the flash drum (separator).',
      'Vapour rises and leaves by the top outlet — a pressure control valve (PV) maintains drum operating pressure.',
      'Liquid settles and leaves by the bottom outlet — a level control valve (LC) maintains liquid level.',
      'The two outlet streams are in thermodynamic equilibrium at the drum pressure.',
    ],
    applications: ['Separation of light ends from heavy hydrocarbon streams in refineries', 'Removal of dissolved gases from liquids', 'Pre-treatment of feeds before further separation (distillation, absorption, etc.)', 'Used in evaporation, degassing and stabilizer units'],
    advantages: ['Very simple — single stage, no trays or packing', 'No heat is added — energy comes from the sensible heat of the feed', 'Fast, continuous operation', 'Cheap compared to a column'],
    limitations: ['Only one equilibrium stage — limited separation', 'Separation depends on pressure drop and feed condition', 'Lower drum pressure ⇒ more vapour formed (less liquid product)'],
    keyPoints: [
      'It is a single-stage, equilibrium unit operation.',
      'No heat is added. The energy required for vaporization is obtained by the sensible heat of the feed.',
      'The operation is adiabatic (no heat exchange).',
      'The vapour and the liquid leaving the drum are in thermodynamic equilibrium.',
    ],
    formulas: [
      { name: 'Total material balance', f: 'F = V + L' },
      { name: 'Component balance', f: 'F·zᵢ = V·yᵢ + L·xᵢ' },
      { name: 'Flash (vapour) fraction', f: 'V/F = (hF − hL) / (hV − hL)' },
    ],
    extraNote: 'hF = enthalpy of feed, hV = enthalpy of vapour, hL = enthalpy of liquid — all at the flash drum pressure. F = feed (kmol/h), V = vapour, L = liquid, z/y/x = mole fractions of component i in feed / vapour / liquid.',
    legend: [
      { c: '#2563eb', t: 'Feed — liquid at P₁, T₁' },
      { c: '#d9480f', t: 'Throttling valve — pressure drop causes flash' },
      { c: '#f08c00', t: 'Vapour outlet → condenser / further processing' },
      { c: '#1a7f4e', t: 'Liquid outlet → further processing' },
    ],
    trouble: [
      { s: 'Insufficient flash', c: ['Pressure not reduced enough', 'High initial temperature'], a: ['Reduce pressure', 'Control feed temperature'] },
      { s: 'Low vapour yield', c: ['Low feed temperature', 'High system pressure'], a: ['Increase feed temperature', 'Reduce pressure'] },
      { s: 'Carryover of liquid', c: ['High feed rate', 'Poor inlet device'], a: ['Reduce feed rate', 'Improve inlet device'] },
      { s: 'Temperature not as expected', c: ['Incorrect pressure', 'Temperature control issue'], a: ['Check pressure control', 'Calibrate instruments'] },
      { s: 'Fouling / scaling', c: ['Impurities in feed', 'High solids content'], a: ['Pre-treat feed', 'Clean vessel'] },
      { s: 'Unstable operation', c: ['Fluctuating feed', 'Pressure fluctuations'], a: ['Stabilize feed', 'Pressure control'] },
      { s: 'Safety valve lifting', c: ['Over pressure', 'Valve setting low'], a: ['Check pressure', 'Reset valve'] },
      { s: 'High energy consumption', c: ['Excessive pressure drop', 'Heat loss'], a: ['Optimize pressure', 'Insulate system'] },
    ],
  },

  /* ---------------- STEAM ---------------- */
  {
    id: 'steam',
    name: 'Steam Distillation',
    short: 'Steam',
    ico: '♨️',
    color: '#0ca678',
    tagline: 'Co-distill with steam to pull heat-sensitive, water-immiscible compounds out below their normal boiling point.',
    useWhen: 'Use for volatile, water-immiscible, heat-sensitive compounds (essential oils, aromatics)',
    definition: 'Steam distillation is a separation process in which steam is used to distill volatile, water-immiscible and heat-sensitive compounds at a temperature lower than their normal boiling point.',
    principle: [
      'Steam and the organic compound are immiscible.',
      'The total vapour pressure of the mixture equals the external pressure at a temperature LOWER than the normal boiling point of the organic compound:  P_total = P_water + P_organic.',
      'Hence the mixture boils and volatile compounds distil over with the steam.',
    ],
    steps: [
      'Steam is generated in a boiler and introduced into the distillation vessel.',
      'Steam passes through the material (mixed with water or supported on a tray).',
      'Volatile, water-immiscible compounds vaporize along with steam.',
      'The vapour mixture (steam + organic vapour) passes through the condenser.',
      'In the condenser, vapour is cooled and condensed to liquid.',
      'Distillate is collected in the receiver — since the organic compound and water are immiscible, two separate layers form.',
      'The organic layer (oil) is lighter or heavier than water depending on the compound, and is separated.',
    ],
    applications: ['Extraction of essential oils (eucalyptus, peppermint, rose oil, etc.)', 'Heat-sensitive materials', 'Purification of volatile organic compounds', 'Pharmaceutical and chemical industries', 'Extraction of flavours and fragrances'],
    advantages: ['Distillation at lower temperature', 'Suitable for heat-sensitive materials', 'Prevents decomposition of compounds', 'Simple and easy operation', 'Good for water-immiscible volatile compounds'],
    limitations: ['Compound must be volatile with steam', 'Not suitable for water-soluble compounds', 'Large quantity of steam is required', 'Not suitable for very high-boiling compounds'],
    extras: {
      types: [
        { t: 'Direct steam distillation', d: 'Steam is passed directly into the material.' },
        { t: 'Steam and water distillation', d: 'Material is immersed in water and steam is passed.' },
        { t: 'Water distillation', d: 'Material is boiled directly with water.' },
      ],
    },
    keyNotes: [
      'More volatile compound co-distils with steam.',
      'Lower boiling point due to total vapour pressure (P_water + P_organic = P_external).',
      'Immiscibility between water and organic compound is important.',
    ],
    legend: [
      { c: '#d9480f', t: 'Steam in / heat' },
      { c: '#1971c2', t: 'Mixture of water + organic compound' },
      { c: '#1098ad', t: 'Cooling water in (bottom) / out (top)' },
      { c: '#f08c00', t: 'Organic layer (oil)' },
      { c: '#1a7f4e', t: 'Aqueous layer (water)' },
    ],
    trouble: [
      { s: 'Low distillate rate', c: ['Insufficient steam supply', 'Steam leaks'], a: ['Increase steam flow', 'Check and repair leaks'] },
      { s: 'Poor oil yield / low recovery', c: ['Insufficient contact time', 'High steam rate'], a: ['Increase contact time', 'Optimize steam rate'] },
      { s: 'Emulsion formation', c: ['High oil content in layer', 'Impurities in feed'], a: ['Optimize separator setting', 'Use demulsifier'] },
      { s: 'Foaming', c: ['Impurities / soaps present'], a: ['Reduce steam rate', 'Add antifoam'] },
      { s: 'Condensate not separating', c: ['Dirty separator', 'High oil droplets'], a: ['Clean separator', 'Maintain proper temperature'] },
      { s: 'Carryover of water in distillate', c: ['High steam rate', 'Too much entrainment'], a: ['Reduce steam rate', 'Improve condenser'] },
      { s: 'Unpleasant odor', c: ['Overheating', 'Long distillation time'], a: ['Reduce heat', 'Optimize time'] },
      { s: 'High pressure in system', c: ['Blocked vent', 'Condenser issue'], a: ['Clear vent line', 'Check condenser'] },
    ],
  },

  /* ---------------- VACUUM ---------------- */
  {
    id: 'vacuum',
    name: 'Vacuum Distillation',
    short: 'Vacuum',
    ico: '🌀',
    color: '#4263eb',
    tagline: 'Lower the pressure → lower the boiling point. Distil high-boiling or heat-sensitive liquids gently.',
    useWhen: 'Use for high-boiling or heat-sensitive liquids that would decompose at atmospheric distillation temperatures',
    definition: 'Vacuum distillation is a distillation process carried out at a pressure lower than atmospheric pressure. Due to reduced pressure, the boiling point of the liquid decreases and high-boiling / heat-sensitive liquids can be distilled at lower temperature.',
    principle: [
      'A liquid boils when its vapour pressure becomes equal to the surrounding pressure.',
      'If external pressure is reduced by a vacuum pump, the boiling point of the liquid decreases.',
      'The vapour formed is condensed and the distillate is collected.',
    ],
    steps: [
      'Feed is taken from the feed tank.',
      'It may be preheated in a preheater (if required).',
      'It then enters the heater / reboiler where heat is supplied.',
      'The vacuum pump removes non-condensable gases and reduces the pressure in the system.',
      'Due to low pressure, the liquid boils at lower temperature and vapours are generated.',
      'Vapours rise through the column.',
      'In the column, vapour and liquid contact each other on trays or packing → separation takes place.',
      'Overhead vapours go to the condenser and get condensed.',
      'Condensed liquid is collected in the distillate receiver.',
      'Heavier / less volatile liquid leaves from the bottom as bottom product.',
    ],
    applications: ['Petroleum industry (vacuum gas oil, lube base oils, heavy fractions)', 'Pharmaceutical industry (heat-sensitive compounds)', 'Chemical industry (high-boiling chemicals)', 'Essential oils and fragrances', 'Solvent recovery', 'Edible oil purification'],
    advantages: ['Lower boiling temperature', 'Prevents thermal decomposition', 'Suitable for heat-sensitive materials', 'Better product quality', 'Helps in distillation of high-boiling liquids'],
    limitations: ['Requires vacuum system', 'Leakage of air disturbs operation', 'Vacuum equipment is costly', 'Maintenance of vacuum pump is required', 'Condensation under vacuum is more difficult', 'Foaming and entrainment may occur'],
    keyRelation: 'Pressure ↓ → Boiling point ↓   (P₁ < P₂ ⇒ Tb₁ < Tb₂)',
    comparison: [
      { p: 'Pressure', atm: 'Near atmospheric', vac: 'Below atmospheric' },
      { p: 'Boiling temperature', atm: 'High', vac: 'Low' },
      { p: 'Suitable for', atm: 'Thermally stable materials', vac: 'Heat-sensitive / high-boiling materials' },
      { p: 'Temperature difference', atm: 'High', vac: 'Low' },
      { p: 'Equipment', atm: 'Simple', vac: 'Requires vacuum system' },
      { p: 'Risk of thermal degradation', atm: 'More', vac: 'Less' },
    ],
    extras: {
      components: ['Feed tank', 'Preheater (optional)', 'Heater / reboiler', 'Vacuum distillation column', 'Condenser', 'Distillate receiver', 'Vacuum pump / ejector', 'Vacuum gauge', 'Pressure control system', 'Cooling water system', 'Vacuum breaker', 'Bottom product outlet'],
      pumps: ['Liquid-ring vacuum pump', 'Steam ejector', 'Dry vacuum pump', 'Mechanical pump'],
      column: [
        'Vapour volume is high at low pressure → column diameter is usually large.',
        'Pressure drop in the column must be low.',
        'Packing is often used (Raschig rings, Pall rings, structured packing) for low pressure drop and good mass transfer.',
        'Trays should provide good contact with minimum pressure drop.',
      ],
      keyPoints: [
        'Pressure ↓ → Boiling point ↓.',
        'Main purpose is to reduce operating temperature.',
        'Useful for high-boiling / heat-sensitive liquids.',
        'Low pressure → vapour volume ↑.',
        'Excessive pressure drop increases boiling temperature.',
        'Vacuum pump maintains low pressure; equipment must be well sealed.',
      ],
    },
    legend: [
      { c: '#2563eb', t: 'Feed — from feed tank (may be preheated)' },
      { c: '#d9480f', t: 'Heater / reboiler — steam in, condensate out' },
      { c: '#4263eb', t: 'Vacuum pump / ejector — removes non-condensables' },
      { c: '#1a7f4e', t: 'Distillate (overhead product)' },
      { c: '#5b6675', t: 'Bottom product — less volatile liquid' },
    ],
    trouble: [
      { s: 'High boiling at low temperature', c: ['Vacuum not achieved', 'Air leaks'], a: ['Check vacuum system', 'Eliminate leaks'] },
      { s: 'Low throughput', c: ['Insufficient heating', 'Fouled reboiler'], a: ['Increase heating', 'Clean reboiler'] },
      { s: 'Foaming', c: ['Decomposition of material', 'Too high vacuum'], a: ['Reduce vacuum level', 'Control temperature'] },
      { s: 'Back diffusion of air', c: ['Vacuum breaker failure', 'Leak in system'], a: ['Check vacuum breaker', 'Repair leaks'] },
      { s: 'Bumping', c: ['Sudden pressure change', 'Superheated liquid'], a: ['Boil gently', 'Use boiling chips'] },
      { s: 'Low product quality', c: ['Thermal decomposition', 'High temperature'], a: ['Reduce temperature', 'Improve vacuum'] },
      { s: 'Condenser overload', c: ['High vapour flow', 'Inadequate cooling'], a: ['Increase cooling', 'Reduce feed rate'] },
      { s: 'Oil carryover in distillate', c: ['High vapour velocity', 'Damaged demister'], a: ['Reduce vapour rate', 'Check demister'] },
    ],
  },

  /* ---------------- AZEOTROPIC ---------------- */
  {
    id: 'azeotropic',
    name: 'Azeotropic Distillation',
    short: 'Azeotropic',
    ico: '🧬',
    color: '#2f9e44',
    tagline: 'Add an entrainer to destroy or shift the azeotropic point so an azeotropic mixture can finally be separated.',
    useWhen: 'Use when the mixture forms an azeotrope and ordinary fractional distillation cannot go beyond it',
    definition: 'Azeotropic distillation is a special distillation used to separate liquid mixtures which form azeotropes and cannot be completely separated by ordinary fractional distillation.',
    principle: [
      'An azeotrope is a constant-boiling mixture: at the azeotropic composition the vapour composition is identical to the liquid composition, so no change in composition occurs beyond this point. Types: (i) minimum-boiling azeotrope, (ii) maximum-boiling azeotrope.',
      'An additional substance called an entrainer is added to the azeotropic mixture. It changes the relative volatility of the components and destroys or shifts the azeotropic point so that the components can be separated.',
    ],
    steps: [
      'Feed (azeotropic mixture) and entrainer are fed to the distillation column.',
      'In the reboiler, the mixture is partially vaporized.',
      'Due to the presence of the entrainer, the relative volatility of key components changes.',
      'Vapour rises in the column and liquid flows down.',
      'Overhead vapour is condensed in the condenser.',
      'Condensed liquid goes to the decanter where two liquid phases are formed.',
      'One phase (organic / entrainer rich) is returned to the column as reflux.',
      'The other phase (product rich) is withdrawn as distillate.',
      'Bottoms may be water-rich or the heavy component, depending on the system.',
    ],
    applications: ['Solvent dehydration and purification', 'High-purity product manufacture', 'Difficult separations that form azeotropes', 'Pharmaceutical & chemical industries'],
    advantages: ['Separation of azeotropic mixtures is possible', 'High purity of products can be obtained', 'Effective for difficult separations', 'Useful in solvent dehydration and purification'],
    limitations: ['Extra entrainer is required', 'Additional equipment (decanter, entrainer recovery) increases cost', 'Energy consumption is more', 'Entrainer must be recovered and recycled', 'Not suitable if entrainer forms an azeotrope difficult to break'],
    extras: {
      entrainer: [
        'A high-boiling compound added in small quantity.',
        'It should be more volatile than one component and less volatile than the other.',
        'It should form a minimum-boiling azeotrope with one of the components.',
        'It should be easily recovered and recycled.',
        'It should be chemically stable and inexpensive.',
      ],
      examples: [
        'Ethanol–water system (with benzene as entrainer)',
        'Isopropanol–water system (with cyclohexane)',
        'Acetic acid–water system',
        'Nitrobenzene–water system',
      ],
    },
    comparison: [
      { p: 'Mixture', az: 'Forms azeotrope', or: 'Does not form azeotrope' },
      { p: 'Separation', az: 'Possible with entrainer', or: 'Complete based on volatility' },
      { p: 'Entrainer', az: 'Required', or: 'Not required' },
      { p: 'Relative volatility', az: 'Modified by entrainer', or: 'Natural volatility' },
      { p: 'Equipment', az: 'Column + decanter', or: 'Column + condenser' },
      { p: 'Product', az: 'High purity', or: 'Depends on system' },
      { p: 'Complexity', az: 'More complex', or: 'Relatively simple' },
    ],
    keyPoint: 'Azeotropic distillation works by changing the VLE behaviour of the system using an entrainer so that the azeotropic mixture can be separated. Two liquid phases form in the decanter because the entrainer and water are immiscible.',
    legend: [
      { c: '#2f9e44', t: 'Feed (azeotropic mixture)' },
      { c: '#f08c00', t: 'Entrainer — high-boiling, small quantity' },
      { c: '#e8590c', t: 'Organic / entrainer-rich phase (decanter top) → reflux' },
      { c: '#1971c2', t: 'Water-rich / aqueous phase (decanter bottom) → product' },
      { c: '#5b6675', t: 'Bottoms (residue)' },
    ],
    trouble: [
      { s: 'Azeotropic composition not broken', c: ['Improper entrainer', 'Insufficient entrainer'], a: ['Select proper entrainer', 'Increase entrainer feed'] },
      { s: 'Low purity of product', c: ['Low reflux ratio', 'Insufficient stages'], a: ['Increase reflux', 'Increase stages'] },
      { s: 'High entrainer in product', c: ['Poor separation', 'High reboiler temperature'], a: ['Improve separation', 'Reduce temperature'] },
      { s: 'Loss of entrainer', c: ['Carryover in distillate', 'High boil entrainer'], a: ['Improve reflux', 'Recover entrainer'] },
      { s: 'Emulsion formation', c: ['Presence of water', 'Incompatible liquids'], a: ['Remove water', 'Add demulsifier'] },
      { s: 'High energy consumption', c: ['High reflux ratio', 'Inefficient condenser'], a: ['Optimize reflux', 'Improve condenser'] },
      { s: 'Irregular operation', c: ['Unstable feed', 'Control issues'], a: ['Stabilize feed', 'Check control loops'] },
    ],
  },

  /* ---------------- EXTRACTIVE ---------------- */
  {
    id: 'extractive',
    name: 'Extractive Distillation',
    short: 'Extractive',
    ico: '🧴',
    color: '#e8590c',
    tagline: 'A high-boiling solvent changes the relative volatility (α) of close-boiling or azeotropic pairs so a column can finally separate them.',
    useWhen: 'Use to separate close-boiling mixtures (small α) or azeotropic mixtures',
    definition: 'Extractive distillation is a separation process in which a high-boiling solvent (entraining solvent) is added to the feed mixture to change the relative volatility of the components and thus achieve separation by distillation.',
    principle: [
      'The entrainer (solvent) interacts preferentially with one of the components in the feed.',
      'This changes the relative volatility between the components, i.e. increases α (relative volatility).',
      'As a result, the components can be separated in the distillation column. The solvent is recovered and recycled — it does not appear in the distillate (for a high-boiling entrainer).',
    ],
    steps: [
      'Feed (A + B mixture) enters the distillation column near the top.',
      'Entrainer (high-boiling solvent) is added to the upper part of the column.',
      'The solvent interacts preferentially with one component, raising α.',
      'Reboiler generates vapour; vapour rises, liquid flows down the column.',
      'Component A (more volatile) leaves as distillate overhead after the condenser.',
      'Bottoms (rich in entrainer + less volatile component B) go to the solvent recovery column.',
      'Solvent is recycled to the main column; product B is withdrawn from the recovery column.',
    ],
    applications: ['Azeotropic mixtures (when an azeotrope forms at given pressure)', 'Close-boiling mixtures (small α)', 'High-purity products without drastic column pressure change', 'Petroleum and petrochemical separations'],
    advantages: ['Can break azeotropes', 'Improves relative volatility greatly', 'High-purity products can be obtained', 'Applicable to a wide range of systems'],
    limitations: ['Requires additional solvent', 'More energy due to solvent recovery', 'More complex (extra column)', 'Cost of solvent and recovery'],
    formulas: [
      { name: 'Relative volatility', f: 'α_AB = (yA / xA) / (yB / xB)' },
      { name: 'Effect of entrainer', f: 'α ≈ 1 (difficult)  →  α ≫ 1 (easy)' },
    ],
    extras: {
      types: [
        { t: 'High-boiling entrainer', d: 'Less volatile than both components; mostly remains in the bottom; needs a solvent recovery column.' },
        { t: 'Low-boiling entrainer', d: 'More volatile than both components; leaves with the overhead vapour; needs solvent recovery from the distillate.' },
      ],
      good: [
        'Selective towards one of the components',
        'High boiling point (usually non-volatile)',
        'Chemically stable and inert',
        'Low toxicity and non-corrosive',
        'Easy to separate from products',
        'Affordable and readily available',
      ],
      common: ['Glycols (EG, DEG, TEG)', 'Glycerol', 'Sulfolane', 'Dimethyl sulfoxide (DMSO)', 'N-Methyl pyrrolidone (NMP)', 'Acetamide'],
      examples: [
        'Benzene–cyclohexane (use sulfolane)',
        'Ethanol–water (use glycerol, EG)',
        'Acetone–chloroform (use DMSO)',
        'Acetic acid–water (use glycols)',
        'Many petrochemical separations',
      ],
    },
    comparison: [
      { p: 'Solvent used', az: 'Entrainer (may form azeotrope)', ex: 'Entraining solvent (does not form azeotrope)' },
      { p: 'Distillate', az: 'Entrainer may appear in distillate', ex: 'Entrainer does not appear in distillate (high boiling)' },
      { p: 'Overhead', az: 'Often needs decanter (if heterogeneous)', ex: 'Usually homogeneous (no decanter)' },
      { p: 'Relative volatility', az: 'Changes by forming new azeotrope', ex: 'Changes by altering VLE' },
      { p: 'Recovery', az: 'Decanter + recycle', ex: 'Solvent recovery column' },
      { p: 'Use', az: 'For azeotropic mixtures', ex: 'For close-boiling or azeotropic mixtures' },
    ],
    keyPoint: 'Extractive distillation uses a high-boiling solvent to change the relative volatility between components and enables separation of difficult mixtures. More stages or higher reflux may be required; the solvent is recovered and recycled.',
    legend: [
      { c: '#2563eb', t: 'Feed — A + B mixture' },
      { c: '#e8590c', t: 'Entrainer (solvent) — added near the top' },
      { c: '#1a7f4e', t: 'Distillate — component A' },
      { c: '#5b6675', t: 'Bottoms — product B + entrainer → recovery column' },
    ],
    trouble: [
      { s: 'Low separation factor', c: ['Wrong solvent', 'Less solvent'], a: ['Select proper solvent', 'Increase solvent amount'] },
      { s: 'High solvent in product', c: ['Insufficient stages', 'Low reflux'], a: ['Increase stages', 'Increase reflux'] },
      { s: 'Solvent loss', c: ['Carryover in distillate', 'High vapour rate'], a: ['Reduce vapour rate', 'Improve reflux'] },
      { s: 'High energy consumption', c: ['High solvent flow', 'Inefficient reboiler'], a: ['Optimize solvent flow', 'Improve efficiency'] },
      { s: 'Corrosion', c: ['Incompatible solvent'], a: ['Select compatible solvent / material'] },
      { s: 'Foaming', c: ['Solvent + feed interaction'], a: ['Reduce vapour rate', 'Add antifoam'] },
      { s: 'Difficulty in solvent recovery', c: ['Close boiling points', 'Improper column design'], a: ['Redesign column', 'Adjust pressure'] },
      { s: 'Poor product purity', c: ['Improper solvent ratio', 'Insufficient contact'], a: ['Optimize solvent/feed ratio', 'Increase contact time'] },
    ],
  },
];

/* ---------------- TRUBLESHOOTER GENERAL ---------------- */
const GENERAL_TIPS = [
  'Maintain proper feed quality and steady feed rate.',
  'Ensure proper heat input and uniform distribution.',
  'Keep condensers and reboilers clean.',
  'Monitor pressure, temperature and levels regularly.',
  'Follow preventive maintenance to avoid downtime.',
];

const ABBREVIATIONS = [
  { t: 'Temp', d: 'Temperature' },
  { t: 'Reflux', d: 'Return of condensed liquid to column' },
  { t: 'Feed', d: 'Raw material inlet' },
  { t: 'Reboiler', d: 'Heater at bottom of column' },
  { t: 'Condenser', d: 'Heat exchanger at top of column' },
  { t: 'V.L.V.', d: 'Vapour–Liquid Equilibrium' },
];

/* ---------------- GLOSSARY ---------------- */
const GLOSSARY = [
  { t: 'Azeotrope', d: 'A constant-boiling mixture: at the azeotropic composition, vapour composition equals liquid composition, so no further separation by ordinary distillation is possible. Types: minimum-boiling and maximum-boiling.' },
  { t: 'Bubble point', d: 'Temperature at which a liquid mixture first starts to boil at a given pressure — the dew/bubble curve on a T-x-y diagram.' },
  { t: 'Bottoms / Residue', d: 'The less volatile liquid leaving from the bottom of the column (or still).' },
  { t: 'Condensate', d: 'Liquid formed when vapour is cooled and condensed (e.g. in the condenser or steam traps).' },
  { t: 'Condenser', d: 'Heat exchanger at the top of the system that cools and condenses overhead vapours into liquid.' },
  { t: 'Decanter', d: 'A separator in which two immiscible liquid phases (e.g. entrainer-rich organic and water-rich aqueous) separate by gravity; used in azeotropic distillation.' },
  { t: 'Distillate', d: 'The top (overhead) product — condensed liquid rich in the more volatile component, collected in a receiver.' },
  { t: 'Dew point', d: 'Temperature at which a vapour first starts to condense at a given pressure; paired with the bubble point curve on VLE diagrams.' },
  { t: 'Entrainment', d: 'Liquid droplets being carried up with the vapour (or solvent carried into the distillate). Reduced by lowering vapour velocity and maintaining internals.' },
  { t: 'Entrainer', d: 'An added substance (usually high-boiling) in azeotropic / extractive distillation that changes the relative volatility or destroys the azeotropic point. Must be recoverable and recyclable.' },
  { t: 'Feed', d: 'The raw material / mixture to be separated, introduced into the still or column at the feed inlet.' },
  { t: 'Flash', d: 'Partial vaporization caused by a sudden pressure reduction (throttling) of a liquid at nearly constant temperature — the basis of flash distillation.' },
  { t: 'Flash fraction (V/F)', d: 'Fraction of feed that vaporizes in a flash drum: V/F = (hF − hL)/(hV − hL). Lower drum pressure ⇒ more vapour formed.' },
  { t: 'Flooding', d: 'Failure mode when vapour velocity is too high and liquid cannot flow down the column; vapour is carried up and separation stops. Fix: reduce vapour / feed rate.' },
  { t: 'Fractionating column', d: 'Tall column packed with trays or packing that provides repeated vapour–liquid contact for separating close-boiling mixtures.' },
  { t: 'Miscible / Immiscible', d: 'Miscible liquids mix in all proportions; immiscible liquids (e.g. water and essential oil) form two layers. Steam distillation relies on immiscibility.' },
  { t: 'Overhead', d: 'The top section of a column where the richest vapour in the light component leaves to the condenser.' },
  { t: 'Packing', d: 'Stacked internals (Raschig rings, Pall rings, saddles, structured sheet / Mellapak) providing surface area for vapour–liquid contact; preferred in vacuum service for low pressure drop.' },
  { t: 'Reboiler', d: 'Heater at the bottom of the column (steam in, condensate out) that partially vaporizes the liquid to generate rising vapour.' },
  { t: 'Reflux', d: 'Part of the condensed overhead liquid returned to the top of the column. More reflux ⇒ better separation but higher energy use. The reflux ratio R = reflux / distillate.' },
  { t: 'Relative volatility (α)', d: 'α_AB = (yA/xA)/(yB/xB). α ≈ 1 means separation is difficult; α ≫ 1 means it is easy. Extractive distillation raises α with a solvent.' },
  { t: 'Still / Stills', d: 'The vessel where the feed is heated and vaporized (e.g. a jacketed kettle in simple distillation).' },
  { t: 'Trays', d: 'Horizontal stages (sieve, valve, bubble-cap) inside a column where rising vapour and falling liquid contact each other.' },
  { t: 'Vapour pressure', d: 'Pressure exerted by a vapour in equilibrium with its liquid. A liquid boils when its vapour pressure equals the external pressure.' },
  { t: 'V.L.E. (Vapour–Liquid Equilibrium)', d: 'Thermodynamic balance between vapour and liquid phases; the basis of all distillation. Shown as bubble/dew (T-x-y) or y-x curves.' },
  { t: 'Vacuum (absolute) pressure', d: 'Pressure lower than atmospheric (vacuum); absolute pressure is measured from perfect vacuum. Lowering pressure lowers the boiling point.' },
  { t: 'Weeping', d: 'Liquid leaking down through tray holes because vapour velocity is too low; reduces separation efficiency. Fix: increase vapour rate or reduce reflux.' },
];

/* ---------------- QUIZ ---------------- */
const QUIZ = [
  {
    q: 'Which method is best for separating two miscible liquids whose boiling points differ by more than 25–30 °C?',
    o: ['Simple distillation', 'Flash distillation', 'Steam distillation', 'Extractive distillation'],
    a: 0,
    w: 'Simple distillation works when the boiling point difference is large (ΔTb > 25–30 °C) or when removing non-volatile impurities.',
  },
  {
    q: 'In fractional distillation, what is the name for the condensed overhead liquid returned to the top of the column?',
    o: ['Bottoms', 'Reflux', 'Residue', 'Distillate'],
    a: 1,
    w: 'Part of the condensed liquid is returned to the column as reflux; the rest is withdrawn as distillate (top product).',
  },
  {
    q: 'In flash distillation the feed is partially vaporized by…',
    o: ['Adding heat in a reboiler', 'A sudden reduction in pressure (throttling)', 'Injecting steam', 'Raising the drum temperature'],
    a: 1,
    w: 'Flash is adiabatic: no heat is added. The sudden pressure drop lowers the boiling point and part of the liquid "flashes" to vapour.',
  },
  {
    q: 'A key difference between flash distillation and simple distillation is that flash…',
    o: ['Uses a long fractionating column', 'Has no trays or packing — it is a single equilibrium stage', 'Requires a decanter', 'Runs under vacuum only'],
    a: 1,
    w: 'Flash distillation is a single-stage equilibrium operation with no trays or packing; separation depends on pressure drop and feed condition.',
  },
  {
    q: 'Why can steam distillation distil an organic compound below its normal boiling point?',
    o: ['Steam adds heat directly to the compound', 'The compound is dissolved in water', 'The total vapour pressure (water + organic) equals the external pressure at a lower temperature, and the liquids are immiscible', 'The pressure is raised above atmospheric'],
    a: 2,
    w: 'Because water and the organic are immiscible, P_total = P_water + P_organic reaches the external pressure at a temperature below the organic\'s normal boiling point.',
  },
  {
    q: 'In vacuum distillation, reducing the system pressure…',
    o: ['Raises the boiling point', 'Lowers the boiling point', 'Has no effect on boiling point', 'Only changes the vapour composition'],
    a: 1,
    w: 'A liquid boils when its vapour pressure equals the surrounding pressure. Lower external pressure ⇒ lower boiling temperature (P₁ < P₂ ⇒ Tb₁ < Tb₂).',
  },
  {
    q: 'Which piece of equipment is essential for vacuum distillation but not for atmospheric distillation?',
    o: ['Reboiler', 'Condenser', 'Vacuum pump / ejector', 'Receiver'],
    a: 2,
    w: 'The vacuum pump (or ejector) removes non-condensable gases and maintains the low pressure in the system.',
  },
  {
    q: 'What is an azeotrope?',
    o: ['A mixture that boils at a very high temperature', 'A constant-boiling mixture where the vapour composition equals the liquid composition', 'A solid formed in a distiller', 'A type of tray used in columns'],
    a: 1,
    w: 'At the azeotropic composition the vapour has the same composition as the liquid, so no change in composition occurs beyond this point.',
  },
  {
    q: 'In azeotropic distillation, the role of the entrainer is to…',
    o: ['Cool the overhead vapour', 'Change the relative volatility and destroy or shift the azeotropic point', 'Increase the column pressure', 'Act as a catalyst'],
    a: 1,
    w: 'The entrainer changes the relative volatility of the components so the azeotropic point is destroyed or shifted and the mixture can be separated.',
  },
  {
    q: 'Why do two liquid phases form in the decanter of an azeotropic distillation unit?',
    o: ['Because the entrainer and water are immiscible', 'Because of high temperature', 'Because of dissolved gases', 'Because of fouling'],
    a: 0,
    w: 'Two liquid phases (organic/entrainer-rich and water-rich) form in the decanter because the entrainer and water are immiscible.',
  },
  {
    q: 'The relative volatility α_AB is defined as…',
    o: ['(xA / yA) / (xB / yB)', '(yA / xA) / (yB / xB)', 'yA + yB', 'xB − xA'],
    a: 1,
    w: 'α_AB = (yA/xA)/(yB/xB). α ≈ 1 means difficult separation; α ≫ 1 means easy separation.',
  },
  {
    q: 'In extractive distillation, adding a high-boiling entrainer moves α…',
    o: ['From ≫ 1 to ≈ 1', 'From ≈ 1 to ≫ 1', 'It stays unchanged', 'To exactly zero'],
    a: 1,
    w: 'The solvent interacts preferentially with one component, raising relative volatility from near 1 (difficult) to much greater than 1 (easy).',
  },
  {
    q: 'Why is a solvent recovery column needed in extractive distillation (high-boiling entrainer)?',
    o: ['To cool the feed', 'The entrainer exits in the bottoms with product B and must be recovered and recycled', 'To create the vacuum', 'To remove non-condensable gases'],
    a: 1,
    w: 'The high-boiling entrainer mostly remains in the bottom; a recovery column separates product B from the solvent so the solvent can be recycled.',
  },
  {
    q: 'Flooding in a fractionating column is usually caused by high vapour velocity. The corrective action is to…',
    o: ['Increase reflux', 'Reduce vapour / feed rate', 'Add more trays', 'Raise the reboiler temperature'],
    a: 1,
    w: 'Flooding occurs when vapour velocity is too high (or feed rate excessive); reduce the vapour rate and feed rate.',
  },
  {
    q: '"Weeping" in a tray column happens when…',
    o: ['Vapour velocity is too low and liquid leaks through the tray holes', 'The condenser is overcooled', 'The vacuum is too high', 'The feed is too hot'],
    a: 0,
    w: 'With low vapour velocity (or high reflux), liquid weeps through the tray holes instead of pooling, which cuts separation efficiency. Fix: increase vapour rate / reduce reflux.',
  },
  {
    q: 'Which distillation type is used when high-temperature distillation is NOT possible (heat-sensitive, high-boiling liquids)?',
    o: ['Simple distillation', 'Steam distillation', 'Vacuum distillation', 'Flash distillation'],
    a: 2,
    w: 'Vacuum distillation lowers the operating temperature by lowering the pressure — protecting heat-sensitive or high-boiling liquids from thermal decomposition.',
  },
];

/* ---------------- COMPARE PAGE ---------------- */
const COMPARE_ROWS = [
  { p: 'Key idea', simple: 'One stage: light component vaporizes, condenses, collected', fractional: 'Many stages (trays/packing) for repeated vapour–liquid contact', flash: 'Partial vaporization by sudden pressure drop (no heat)', steam: 'Co-distil with steam; P_water + P_organic = P_external', vacuum: 'Lower pressure ⇒ lower boiling temperature', azeotropic: 'Entrainer destroys/shifts the azeotropic point', extractive: 'Solvent raises relative volatility α' },
  { p: 'Pressure', simple: 'Usually atmospheric', fractional: 'Usually atmospheric', flash: 'Feed at high P, drum at lower P', steam: 'Near atmospheric', vacuum: 'Below atmospheric', azeotropic: 'Atmospheric (design-dependent)', extractive: 'Atmospheric (design-dependent)' },
  { p: 'Best used for', simple: 'Large ΔTb > 25–30 °C; non-volatile impurities', fractional: 'Close-boiling mixtures; crude oil; alcohol', flash: 'Light-ends removal, degassing, pre-separation', steam: 'Heat-sensitive, water-immiscible volatiles (oils)', vacuum: 'High-boiling / heat-sensitive liquids', azeotropic: 'Azeotropic mixtures (e.g. ethanol–water)', extractive: 'Close-boiling (small α) or azeotropic pairs' },
  { p: 'Main equipment', simple: 'Jacketed still + condenser + receivers', fractional: 'Fractionating column, reboiler, condenser, reflux drum', flash: 'Throttling valve + flash drum + control valves', steam: 'Still + condenser + separating-funnel receiver', vacuum: 'Column + reboiler + condenser + vacuum pump', azeotropic: 'Column + decanter + reboiler/condenser', extractive: 'Column + solvent recovery column' },
  { p: 'Biggest strength', simple: 'Cheap, simple, robust', fractional: 'High purity, continuous operation', flash: 'Simplest possible separation stage', steam: 'Boils below normal boiling point', vacuum: 'Protects against thermal decomposition', azeotropic: 'Breaks the azeotrope itself', extractive: 'Greatly increases α; no new azeotrope' },
  { p: 'Main drawback', simple: 'Cannot separate close-boiling liquids', fractional: 'Cost, energy, complexity', flash: 'Single stage only — limited purity', steam: 'Needs water-immiscible, steam-volatile compound', vacuum: 'Vacuum system, leaks, cost', azeotropic: 'Extra entrainer + decanter + recycle', extractive: 'Extra solvent + recovery column + energy' },
];
