"""Export OpenPyTEA data + parity expectations for the static webapp.

Generates:
  webapp/js/data.js        - correlations, CEPCI, factors, MACRS, presets, learn content
  webapp/test/expected.json - engine outputs used by the Node parity harness

Run:  python tools/export_webapp_data.py
"""
from __future__ import annotations

import ast
import json
import math
import sys
from copy import deepcopy
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

WEBAPP = ROOT / "webapp"
( WEBAPP / "js").mkdir(parents=True, exist_ok=True)
(WEBAPP / "test").mkdir(parents=True, exist_ok=True)

import tea_core as T  # noqa: E402
import content as C  # noqa: E402
from openpytea.equipment import CostCorrelationDB, CEPCI_DF  # noqa: E402
from openpytea.equipment import Equipment  # noqa: E402
from openpytea.plant import Plant, _MACRS_HALF_YEAR  # noqa: E402
from openpytea import analysis as OA  # noqa: E402


def js_num(x):
    """Convert numpy/pandas scalars to JSON-safe python values."""
    if x is None:
        return None
    if isinstance(x, float):
        return x if math.isfinite(x) else None
    if isinstance(x, (np.floating,)):
        f = float(x)
        return f if math.isfinite(f) else None
    if isinstance(x, (np.integer,)):
        return int(x)
    if isinstance(x, (np.bool_, bool)):
        return bool(x)
    if isinstance(x, (np.ndarray,)):
        return [js_num(v) for v in x.tolist()]
    if isinstance(x, (list, tuple)):
        return [js_num(v) for v in x]
    if pd.isna(x):
        return None
    return x


# ----------------------------------------------------------------------------
# 1. data.js
# ----------------------------------------------------------------------------
def export_data_js():
    db = CostCorrelationDB()
    df = db.df
    rows = []
    for _, r in df.iterrows():
        rows.append({
            "key": r.get("key"),
            "category": r.get("category"),
            "type": js_num(r.get("type")) if pd.notna(r.get("type")) else None,
            "form": r.get("form"),
            "s_lower": js_num(r.get("s_lower")),
            "s_upper": js_num(r.get("s_upper")),
            "s2_lower": js_num(r.get("s2_lower")),
            "s2_upper": js_num(r.get("s2_upper")),
            "upper_parallel": js_num(r.get("upper_parallel")),
            "a": js_num(r.get("a")), "b": js_num(r.get("b")),
            "n": js_num(r.get("n")), "n2": js_num(r.get("n2")),
            "k1": js_num(r.get("k1")), "k2": js_num(r.get("k2")),
            "k3": js_num(r.get("k3")), "k4": js_num(r.get("k4")),
            "k5": js_num(r.get("k5")),
            "s0": js_num(r.get("s0")), "c0": js_num(r.get("c0")),
            "f": js_num(r.get("f")),
            "cost_year": js_num(r.get("cost_year")),
            "default_material": db.default_material_for_key(r.get("key")),
            "unit": js_num(r.get("unit")) if "unit" in df.columns and pd.notna(r.get("unit")) else None,
        })

    cepci = {str(int(y)): float(v) for y, v in CEPCI_DF["cepci"].items()}

    # FLOW_STRIPS lives in app.py (imports streamlit) -> extract via AST.
    app_src = (ROOT / "app.py").read_text()
    flow_strips = {}
    for node in ast.walk(ast.parse(app_src)):
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == "FLOW_STRIPS":
            flow_strips = ast.literal_eval(node.value)

    data = {
        "correlations": rows,
        "cepci": cepci,
        "process_types": Plant.processTypes,
        "loc_factors": Plant.locFactors,
        "macrs": {str(k): [float(x) for x in v] for k, v in _MACRS_HALF_YEAR.items()},
        "equip_process_factors": Equipment.process_factors,
        "material_factors": Equipment.material_factors,
        "presets": json.loads(json.dumps(T.PRESETS, default=str)),
        "learn": {
            "types": json.loads(json.dumps(C.DISTILLATION_TYPES, default=str)),
            "comparison": json.loads(json.dumps(C.COMPARISON_TABLE, default=str)),
            "tips": list(C.GENERAL_TIPS),
            "abbreviations": dict(C.ABBREVIATIONS),
            "flow_strips": flow_strips,
        },
    }
    out = WEBAPP / "js" / "data.js"
    out.write_text(
        "/* AUTO-GENERATED by tools/export_webapp_data.py — DO NOT EDIT. */\n"
        "(function (root) {\n  root.TEA_DATA = "
        + json.dumps(data, allow_nan=False)
        + ";\n})(typeof window !== 'undefined' ? window : globalThis);\n"
    )
    print(f"wrote {out} ({out.stat().st_size/1024:.0f} KB, {len(rows)} correlations)")


# ----------------------------------------------------------------------------
# 2. expected.json (parity expectations)
# ----------------------------------------------------------------------------
def plant_kpis_full(plant):
    plant.calculate_all()
    plant.calculate_purchased_cost()
    g = lambda k: js_num(getattr(plant, k, float("nan")))
    arr = lambda k: [js_num(v) for v in np.atleast_2d(np.asarray(getattr(plant, k), dtype=float)).tolist()]
    return {
        "purchased_cost": g("purchased_cost"), "isbl": g("isbl"),
        "osbl": g("osbl"), "dne": g("dne"), "contigency": g("contigency"),
        "fixed_capital": g("fixed_capital"), "working_capital": g("working_capital"),
        "variable_opex": g("variable_production_costs"),
        "fixed_opex": g("fixed_production_costs"),
        "operating_labor_costs": g("operating_labor_costs"),
        "revenue": g("revenue"), "npv": g("npv"),
        "levelized_cost": g("levelized_cost"),
        "payback_time": g("payback_time"), "roi": g("roi"), "irr": g("irr"),
        "cash_flow": arr("cash_flow"), "prod_array": arr("prod_array"),
        "revenue_array": arr("revenue_array"),
        "capital_cost_array": arr("capital_cost_array"),
        "cash_cost_array": arr("cash_cost_array"),
        "gross_profit_array": arr("gross_profit_array"),
        "depreciation_array": arr("depreciation_array"),
        "tax_paid_array": arr("tax_paid_array"),
        "variable_opex_breakdown": {k: js_num(v) for k, v in plant.variable_opex_breakdown.items()},
        "revenue_breakdown": {k: js_num(v) for k, v in plant.revenue_breakdown.items()},
    }


def export_expected():
    exp = {"presets": {}, "sensitivity": {}, "tornado": {},
           "monte_carlo": {}, "equipment": {}, "edge": {}}

    for name, p in T.PRESETS.items():
        eq_objs, errs = T.build_equipment_list(deepcopy(p["equipment"]))
        assert not errs, (name, errs)
        exp["equipment"][name] = [
            {"name": e.name, "purchased_cost": js_num(e.purchased_cost),
             "direct_cost": js_num(e.direct_cost), "num_units": e.num_units,
             "cost_year": e.cost_year, "material": e.material,
             "material_factor": js_num(e.material_factor)}
            for e in eq_objs
        ]
        plant = T.build_plant(deepcopy(p["plant"]), eq_objs)
        exp["presets"][name] = plant_kpis_full(plant)

    # Sensitivity curves on first preset (scalar plant, fresh each time)
    def fresh(name):
        p = T.PRESETS[name]
        eq_objs, _ = T.build_equipment_list(deepcopy(p["equipment"]))
        return T.build_plant(deepcopy(p["plant"]), eq_objs)

    base = next(iter(T.PRESETS))
    for param, metric in [("fixed_capital", "LCOP"), ("interest_rate", "NPV"),
                          ("feed_ethanol_water", "LCOP"), ("ethanol_distillate", "NPV")]:
        r = OA.sensitivity_data(fresh(base), parameter=param, metric=metric,
                                plus_minus_value=0.2, n_points=9)
        exp["sensitivity"][f"{param}|{metric}"] = {
            "parameter": r["parameter"], "metric": r["metric"],
            "x": js_num(r["curves"][0]["x"]),
            "y": js_num(r["curves"][0]["y"]),
            "baseline": js_num(r["curves"][0]["baseline"]),
        }

    # Tornado
    for metric in ["LCOP", "NPV"]:
        r = OA.tornado_data(fresh(base), plus_minus_value=0.1, metric=metric)
        exp["tornado"][metric] = {
            "baseline": js_num(r["base_value"]),
            "factors": list(r["factors"]),
            "lows": js_num(r["lows"]),
            "highs": js_num(r["highs"]),
        }

    # Monte Carlo (statistical parity only — different PRNG than JS)
    mc = OA.monte_carlo(fresh(base), num_samples=4000, batch_size=4000,
                        random_seed=7)
    summ = {}
    for k, v in mc["metrics"].items():
        v = np.asarray(v, dtype=float)
        fin = v[np.isfinite(v)]
        summ[k] = {"mean": js_num(float(np.mean(fin))) if len(fin) else None,
                   "std": js_num(float(np.std(fin))) if len(fin) else None,
                   "p5": js_num(float(np.percentile(fin, 5))) if len(fin) else None,
                   "p50": js_num(float(np.percentile(fin, 50))) if len(fin) else None,
                   "p95": js_num(float(np.percentile(fin, 95))) if len(fin) else None,
                   "n_finite": int(len(fin)), "n": int(len(v))}
    inp = {}
    for k, v in mc["inputs"].items():
        v = np.asarray(v, dtype=float)
        inp[k] = {"mean": js_num(float(v.mean())), "std": js_num(float(v.std()))}
    exp["monte_carlo"] = {"metrics": summ, "inputs": inp,
                          "num_samples": mc["num_samples"]}

    out = WEBAPP / "test" / "expected.json"
    out.write_text(json.dumps(exp, allow_nan=False))
    print(f"wrote {out} ({out.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    export_data_js()
    export_expected()
